In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals
import os
/
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x  #gpu
except Exception:
  pass
import tensorflow as tf

import cProfile

In [3]:
tf.executing_eagerly()

True

In [4]:
x = [[2.]]
m = tf.matmul(x,x)
print("x matmul x = {}".format(m))

x matmul x = [[4.]]


In [5]:
a = tf.constant([[1,2],
                 [3,4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [7]:
b=tf.add(a,1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [8]:
print(a*b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [9]:
print(tf.matmul(a,b))

tf.Tensor(
[[10 13]
 [22 29]], shape=(2, 2), dtype=int32)


In [10]:
import numpy as np

In [12]:
c=np.multiply(a,b)
print(c)
print(type(c))

[[ 2  6]
 [12 20]]
<class 'numpy.ndarray'>


In [13]:
print(a.numpy())

[[1 2]
 [3 4]]


In [16]:
w=tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss=w*w
grad=tape.gradient(loss,w)
print(grad)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


In [2]:
(x_train,y_train),(x_test,y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train[:10000,:,:]
y_train = y_train[:10000]
x_test = x_test[:1000,:,:]
y_test = y_test[:1000]

In [23]:
np.set_printoptions(threshold=100)

In [3]:
x_test[0,0,0]

0

In [31]:
print(type(x_test))

<class 'numpy.ndarray'>


In [32]:
x_test.shape

(1000, 28, 28)

In [25]:
y_test[:10]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9], dtype=uint8)

In [36]:
x_test[:,:,1]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [45]:
x_test[:,:,2]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [44]:
x_test[2,:,:]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  38, 254, 109,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  87, 252,  82,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [40]:
x_test[:,2,:]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [41]:
x_test[:2]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

In [43]:
np.set_printoptions(threshold=np.inf)

In [6]:
x_train = tf.cast(x_train[...,tf.newaxis]/255, tf.float32),
x_test = tf.cast(x_test[...,tf.newaxis]/255, tf.float32),

#y_train = y_train.astype('float32')
#y_test = y_test.astype('float32')
y_train = tf.keras.utils.to_categorical(y_train,10)
y_test = tf.keras.utils.to_categorical(y_test,10)

In [52]:
y_test[:2]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [10]:
y_train[3]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [11]:
#Build the model using Sequential

mnist_model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32,[3,3],activation='relu',
                          input_shape=(28,28,1)),
    tf.keras.layers.Conv2D(64,[3,3],activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=(2,2)),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(10,activation="softmax")
])

In [12]:
mnist_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 64)        0         
_________________________________________________________________
dropout (Dropout)            (None, 12, 12, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 9216)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               1179776   
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0

In [13]:
mnist_model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3),
                    validation_split=0.1,shuffle=True,
                   loss = tf.keras.losses.categorical_crossentropy,
                   metrics = ["accuracy"])

In [14]:
mnist_model.fit(x_train,y_train,batch_size=128,epochs=10)

Train on 10000 samples
Epoch 1/10
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.2998 - accuracy: 0.1190
Epoch 2/10
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.2807 - accuracy: 0.1582
Epoch 3/10
10000/10000 [==============================] - 17s 2ms/sample - loss: 2.2605 - accuracy: 0.2037
Epoch 4/10
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.2391 - accuracy: 0.2545
Epoch 5/10
10000/10000 [==============================] - 17s 2ms/sample - loss: 2.2110 - accuracy: 0.3055
Epoch 6/10
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.1745 - accuracy: 0.3412
Epoch 7/10
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.1291 - accuracy: 0.3815
Epoch 8/10
10000/10000 [==============================] - 17s 2ms/sample - loss: 2.0696 - accuracy: 0.4139
Epoch 9/10
10000/10000 [==============================] - 15s 2ms/sample - loss: 1.9952 - accuracy: 0.4459
Epoch 10/10
10

In [15]:
mnist_model.fit(x_train,y_train,batch_size=128,epochs=100)

Train on 10000 samples
Epoch 1/100
10000/10000 [==============================] - 15s 2ms/sample - loss: 1.7681 - accuracy: 0.5270
Epoch 2/100
10000/10000 [==============================] - 15s 2ms/sample - loss: 1.6308 - accuracy: 0.5538
Epoch 3/100
10000/10000 [==============================] - 16s 2ms/sample - loss: 1.4970 - accuracy: 0.5799
Epoch 4/100
10000/10000 [==============================] - 15s 2ms/sample - loss: 1.3620 - accuracy: 0.6119
Epoch 5/100
10000/10000 [==============================] - 16s 2ms/sample - loss: 1.2346 - accuracy: 0.6396
Epoch 6/100
10000/10000 [==============================] - 15s 2ms/sample - loss: 1.1486 - accuracy: 0.6541
Epoch 7/100
10000/10000 [==============================] - 16s 2ms/sample - loss: 1.0644 - accuracy: 0.6774
Epoch 8/100
10000/10000 [==============================] - 17s 2ms/sample - loss: 0.9940 - accuracy: 0.7003
Epoch 9/100
10000/10000 [==============================] - 19s 2ms/sample - loss: 0.9390 - accuracy: 0.7132
Epoch

In [16]:
mnist_model.evaluate(x_test,y_test)

1000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.2572028150558472, 0.921]

In [32]:
x_train[0]

<tf.Tensor: id=1, shape=(10000, 28, 28, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0

In [34]:
mnist_model.predict(x_test)

array([[3.3638441e-06, 3.5328119e-07, 1.6367954e-05, ..., 9.9877852e-01,
        6.8224176e-06, 8.7017147e-04],
       [1.7571033e-03, 2.0828759e-04, 9.6168721e-01, ..., 3.7201752e-07,
        2.4478263e-03, 7.0569299e-06],
       [3.5133147e-05, 9.9313557e-01, 1.7939697e-03, ..., 1.1966724e-03,
        1.3200154e-03, 1.8707513e-04],
       ...,
       [9.9983263e-01, 1.3061880e-08, 5.8252118e-07, ..., 2.4542651e-08,
        7.0555751e-07, 2.7015321e-07],
       [7.1590883e-03, 2.8962235e-03, 3.3972992e-03, ..., 1.0921414e-01,
        6.1529994e-01, 1.3601193e-01],
       [3.9599446e-04, 5.2550295e-04, 3.1156186e-03, ..., 4.4925621e-01,
        1.4368535e-03, 4.4075236e-01]], dtype=float32)

In [17]:
#Build the model using Model
inputs = tf.keras.Input(shape=(None,None,1),name="digits")
conv_1 = tf.keras.layers.Conv2D(16,[3,3],activation="relu")(inputs)
conv_2 = tf.keras.layers.Conv2D(16,[3,3],activation="relu")(conv_1)
ave_pool = tf.keras.layers.GlobalAveragePooling2D()(conv_2)
outputs = tf.keras.layers.Dense(10,activation='softmax')(ave_pool)
mnist_model_2 = tf.keras.Model(inputs=inputs,outputs=outputs)


In [27]:
mnist_model_3.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
digits (InputLayer)          [(None, None, None, 1)]   0         
_________________________________________________________________
conv2d_12 (Conv2D)           (None, None, None, 32)    320       
_________________________________________________________________
conv2d_13 (Conv2D)           (None, None, None, 64)    18496     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, None, None, 64)    0         
_________________________________________________________________
dropout_8 (Dropout)          (None, None, None, 64)    0         
_________________________________________________________________
dense_7 (Dense)              (None, None, None, 128)   8320      
_________________________________________________________________
dropout_9 (Dropout)          (None, None, None, 128)   0   

In [18]:
mnist_model_2.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
digits (InputLayer)          [(None, None, None, 1)]   0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, None, None, 16)    160       
_________________________________________________________________
conv2d_3 (Conv2D)            (None, None, None, 16)    2320      
_________________________________________________________________
global_average_pooling2d (Gl (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                170       
Total params: 2,650
Trainable params: 2,650
Non-trainable params: 0
_________________________________________________________________


In [19]:
mnist_model_2.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3),
                    validation_split=0.1,shuffle=True,
                   loss = tf.keras.losses.categorical_crossentropy,
                   metrics = ["accuracy"])

In [21]:
mnist_model_2.fit(x_train,y_train,batch_size=128,epochs=30)

Train on 10000 samples
Epoch 1/30
10000/10000 [==============================] - 5s 529us/sample - loss: 2.3044 - accuracy: 0.1032
Epoch 2/30
10000/10000 [==============================] - 5s 506us/sample - loss: 2.3043 - accuracy: 0.1032
Epoch 3/30
10000/10000 [==============================] - 5s 500us/sample - loss: 2.3042 - accuracy: 0.1032
Epoch 4/30
10000/10000 [==============================] - 5s 515us/sample - loss: 2.3041 - accuracy: 0.1032
Epoch 5/30
10000/10000 [==============================] - 5s 529us/sample - loss: 2.3040 - accuracy: 0.1032
Epoch 6/30
10000/10000 [==============================] - 5s 528us/sample - loss: 2.3039 - accuracy: 0.1032
Epoch 7/30
10000/10000 [==============================] - 5s 532us/sample - loss: 2.3038 - accuracy: 0.1032
Epoch 8/30
10000/10000 [==============================] - 6s 570us/sample - loss: 2.3037 - accuracy: 0.1032
Epoch 9/30
10000/10000 [==============================] - 6s 618us/sample - loss: 2.3036 - accuracy: 0.1032 -
Epo

In [40]:
#Build the model using Model
inputs = tf.keras.Input(shape=(28,28,1),name="digits")
conv_1 = tf.keras.layers.Conv2D(32,[3,3],activation="relu")(inputs)
conv_2 = tf.keras.layers.Conv2D(64,[3,3],activation="relu")(conv_1)
max_pool = tf.keras.layers.MaxPooling2D(pool_size=(2,2))(conv_2)
dropout = tf.keras.layers.Dropout(0.25)(max_pool)
flatten = tf.keras.layers.Flatten()(dropout)
dense_1 = tf.keras.layers.Dense(128,activation="relu")(flatten)
dropout_2 = tf.keras.layers.Dropout(0.5)(dense_1)
outputs = tf.keras.layers.Dense(10,activation="softmax")(dropout_2)

mnist_model_3 = tf.keras.Model(inputs=inputs,outputs=outputs)

In [41]:
mnist_model_3.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3),
                    validation_split=0.1,shuffle=True,
                   loss = tf.keras.losses.categorical_crossentropy,
                   metrics = ["accuracy"])

In [42]:
mnist_model_3.fit(x_train,y_train,batch_size=128,epochs=30)

Train on 10000 samples
Epoch 1/30
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.2976 - accuracy: 0.1077
Epoch 2/30
10000/10000 [==============================] - 15s 2ms/sample - loss: 2.2877 - accuracy: 0.1310
Epoch 3/30
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.2748 - accuracy: 0.1576
Epoch 4/30
10000/10000 [==============================] - 17s 2ms/sample - loss: 2.2628 - accuracy: 0.1880
Epoch 5/30
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.2469 - accuracy: 0.2230
Epoch 6/30
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.2280 - accuracy: 0.2640
Epoch 7/30
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.2050 - accuracy: 0.2961
Epoch 8/30
10000/10000 [==============================] - 16s 2ms/sample - loss: 2.1743 - accuracy: 0.3326
Epoch 9/30
10000/10000 [==============================] - 15s 2ms/sample - loss: 2.1377 - accuracy: 0.3682
Epoch 10/30
10